# Generated by Django 4.2 on 2024-02-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_author_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_type',
            field=models.CharField(choices=[('recording', 'recording'), ('composition', 'Composition')], default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../dml85uj9yqmxekst8gbc', null=True, upload_to='post_images/'),
        ),
    ]
