# Generated by Django 4.2 on 2024-02-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_audio_type_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio_type',
            field=models.CharField(choices=[('recording', 'Recording'), ('composition', 'Composition')], default='', max_length=32),
        ),
    ]
